import type { SavedItemResponse } from "@/lib/api/types";

export const MOCK_ITEMS: SavedItemResponse[] = [
  {
    id: "mock-food-1",
    source_url: "https://www.tiktok.com/@lafoodies/video/7312345678901234567",
    platform: "tiktok",
    category: "food",
    status: "done",
    extracted_data: {
      name: "Kato",
      address: "4000 Sunset Blvd, Los Angeles, CA 90029",
      cuisine: "Japanese-Californian",
      why_visit:
        "Intimate 12-seat omakase helmed by a James Beard nominee. The dashi custard and uni toast are transcendent — book 6 weeks out.",
      price_range: "$$$$",
      dishes_mentioned: ["Uni Toast", "Dashi Custard", "A5 Wagyu"],
    },
    action_taken: "Save to Google Maps",
    thumbnail_url: null,
    created_at: "2026-03-29T06:12:00Z",
    processed_at: "2026-03-29T06:14:00Z",
  },
  {
    id: "mock-food-2",
    source_url: "https://www.instagram.com/p/C8aBcDeFgHi/",
    platform: "instagram",
    category: "food",
    status: "done",
    extracted_data: {
      name: "Roberta's",
      address: "261 Moore St, Brooklyn, NY 11206",
      cuisine: "Neapolitan Pizza",
      why_visit:
        "Wood-fired pies in Bushwick with a cult following. The Bee Sting (soppressata + honey) is worth the 2-hour wait.",
      price_range: "$$",
      dishes_mentioned: ["Bee Sting", "Margherita", "Fresh Mozzarella"],
    },
    action_taken: "Save to Google Maps",
    thumbnail_url: null,
    created_at: "2026-03-28T14:30:00Z",
    processed_at: "2026-03-28T14:32:00Z",
  },
  {
    id: "mock-recipe-1",
    source_url: "https://www.youtube.com/watch?v=abc123def456",
    platform: "youtube",
    category: "recipe",
    status: "done",
    extracted_data: {
      dish_name: "Crispy Smash Burgers",
      ingredients: [
        "80/20 ground beef (150g per patty)",
        "Martin's potato rolls",
        "American cheese slices",
        "White onion, thinly sliced",
        "Pickles",
        "Smash sauce: mayo, ketchup, mustard, pickle brine",
        "Salt & pepper",
      ],
      steps: [
        "Form loose 150g beef balls — do NOT compact",
        "Get cast iron screaming hot with thin layer of butter",
        "Place ball, smash hard with spatula within 10 seconds",
        "Season with salt, pepper immediately",
        "Cook 2 min until edges are crispy and dark",
        "Add onions, flip, add cheese, cover for 30 sec",
        "Toast bun in same pan, sauce both sides",
        "Stack double patty, pickles, onions",
      ],
      prep_time_minutes: 10,
      cook_time_minutes: 8,
      servings: 2,
    },
    action_taken: "Copy ingredient list",
    thumbnail_url: null,
    created_at: "2026-03-28T20:00:00Z",
    processed_at: "2026-03-28T20:02:00Z",
  },
  {
    id: "mock-recipe-2",
    source_url: "https://www.instagram.com/reel/DaBcDeFgHiJ/",
    platform: "instagram",
    category: "recipe",
    status: "done",
    extracted_data: {
      dish_name: "Matcha Tiramisu",
      ingredients: [
        "500g mascarpone",
        "4 egg yolks",
        "80g sugar",
        "2 tbsp ceremonial matcha powder",
        "300ml heavy cream",
        "Ladyfinger biscuits (200g)",
        "Matcha simple syrup for dipping",
      ],
      steps: [
        "Whisk egg yolks and sugar to pale ribbon",
        "Fold in mascarpone until smooth",
        "Whip cream to soft peaks, fold into mascarpone",
        "Brew strong matcha syrup, cool completely",
        "Dip ladyfingers briefly, layer in dish",
        "Alternate cream and ladyfinger layers x3",
        "Dust matcha on top, refrigerate 4+ hours",
      ],
      prep_time_minutes: 25,
      cook_time_minutes: 0,
      servings: 8,
    },
    action_taken: "Copy ingredient list",
    thumbnail_url: null,
    created_at: "2026-03-27T16:45:00Z",
    processed_at: "2026-03-27T16:47:00Z",
  },
  {
    id: "mock-fitness-1",
    source_url: "https://www.tiktok.com/@fitcoach/video/7198765432109876543",
    platform: "tiktok",
    category: "fitness",
    status: "done",
    extracted_data: {
      workout_name: "20-Minute AMRAP Circuit",
      exercises: [
        { name: "Burpees", sets: 1, reps: "10" },
        { name: "Kettlebell Swings", sets: 1, reps: "15" },
        { name: "Box Jumps", sets: 1, reps: "10" },
        { name: "Push-ups", sets: 1, reps: "15" },
        { name: "Mountain Climbers", sets: 1, reps: "20" },
      ],
      muscle_groups: ["Full body", "Core", "Glutes", "Chest"],
      duration_minutes: 20,
      difficulty: "Intermediate",
    },
    action_taken: "Save to my routine",
    thumbnail_url: null,
    created_at: "2026-03-29T07:00:00Z",
    processed_at: "2026-03-29T07:02:00Z",
  },
  {
    id: "mock-fitness-2",
    source_url: "https://www.youtube.com/watch?v=pullday123",
    platform: "youtube",
    category: "fitness",
    status: "done",
    extracted_data: {
      workout_name: "Pull Day — Back & Biceps",
      exercises: [
        { name: "Weighted Pull-ups", sets: 4, reps: "6–8" },
        { name: "Pendlay Row", sets: 4, reps: "5" },
        { name: "Cable Pulldown", sets: 3, reps: "12" },
        { name: "Face Pulls", sets: 3, reps: "15" },
        { name: "Hammer Curls", sets: 3, reps: "10" },
        { name: "Incline DB Curl", sets: 3, reps: "12" },
      ],
      muscle_groups: ["Lats", "Rhomboids", "Biceps", "Rear delts"],
      duration_minutes: 55,
      difficulty: "Advanced",
    },
    action_taken: "Save to my routine",
    thumbnail_url: null,
    created_at: "2026-03-26T09:30:00Z",
    processed_at: "2026-03-26T09:32:00Z",
  },
  {
    id: "mock-howto-1",
    source_url: "https://www.youtube.com/watch?v=homelab456",
    platform: "youtube",
    category: "how-to",
    status: "done",
    extracted_data: {
      title: "Set Up a Home Server with Proxmox",
      summary:
        "Complete guide to turning an old PC into a virtualization server running Proxmox VE with VMs for Plex, Pi-hole, and Nextcloud.",
      steps: [
        "Download Proxmox VE ISO and flash to USB drive",
        "Boot from USB, install to SSD (separate from VMs)",
        "Configure static IP in /etc/network/interfaces",
        "Create ZFS pool across HDDs for VM storage",
        "Set up VM template from Ubuntu Server 22.04",
        "Deploy Plex VM: 4 cores, 8GB RAM, GPU passthrough",
        "Deploy Pi-hole VM: 1 core, 512MB RAM, set as DNS",
        "Deploy Nextcloud VM: 2 cores, 4GB RAM, mount ZFS share",
        "Configure Nginx reverse proxy with SSL (Cloudflare tunnel)",
        "Set up automated Proxmox Backup Server snapshots",
      ],
    },
    action_taken: "Save as guide",
    thumbnail_url: null,
    created_at: "2026-03-27T21:00:00Z",
    processed_at: "2026-03-27T21:02:00Z",
  },
  {
    id: "mock-howto-2",
    source_url: "https://www.instagram.com/p/sourdough789/",
    platform: "instagram",
    category: "how-to",
    status: "done",
    extracted_data: {
      title: "DIY Sourdough Starter from Scratch",
      summary:
        "7-day process to cultivate a wild yeast starter using only flour and water. Ready to bake by day 7.",
      steps: [
        "Day 1: Mix 50g whole wheat flour + 50g warm water in jar",
        "Day 2: Discard half, feed 50g flour + 50g water",
        "Day 3–4: Repeat discards, bubbles should appear",
        "Day 5: Switch to 1:5:5 ratio (starter:flour:water)",
        "Day 6: Starter should double in 4–6 hours after feeding",
        "Day 7: Float test — drop teaspoon in water, if it floats it's ready",
        "Maintain weekly: feed 1:5:5, store in fridge if baking <weekly",
      ],
    },
    action_taken: "Save as guide",
    thumbnail_url: null,
    created_at: "2026-03-25T11:00:00Z",
    processed_at: "2026-03-25T11:01:00Z",
  },
  {
    id: "mock-video-1",
    source_url: "https://www.youtube.com/watch?v=naval_wealth",
    platform: "youtube",
    category: "video-analysis",
    status: "done",
    extracted_data: {
      title: "Naval Ravikant — How to Get Rich (Without Getting Lucky)",
      summary:
        "Naval outlines a systematic framework for building wealth: seek specific knowledge (what you'd do for free), build or invest in businesses with leverage (code, media, capital), and let compounding do the work. Accountability and equity ownership are non-negotiable. Avoid trading time for money at every opportunity.",
      key_points: [
        "Wealth is assets that earn while you sleep — not income",
        "Specific knowledge: authentic expertise that can't be trained",
        "Leverage: code and media have zero marginal cost of replication",
        "Seek accountability — own your outcomes, take risks openly",
        "Judgment from experience is worth more than effort or time",
        "Play long-term games with long-term people",
      ],
    },
    action_taken: "Copy summary",
    thumbnail_url: null,
    created_at: "2026-03-28T19:00:00Z",
    processed_at: "2026-03-28T19:01:00Z",
  },
  {
    id: "mock-other-1",
    source_url: "https://twitter.com/paulg/status/1234567890",
    platform: "twitter",
    category: "other",
    status: "done",
    extracted_data: {
      title: "Paul Graham on startup mistakes",
      summary:
        "The biggest mistake early-stage founders make is optimizing for the appearance of progress rather than actual progress. Building in public looks like work; talking to users IS work.",
    },
    action_taken: "Copy summary",
    thumbnail_url: null,
    created_at: "2026-03-29T05:00:00Z",
    processed_at: "2026-03-29T05:01:00Z",
  },
  {
    id: "mock-pending-1",
    source_url: "https://www.tiktok.com/@gymrat/video/7312000000000000001",
    platform: "tiktok",
    category: "other",
    status: "pending",
    extracted_data: null,
    action_taken: null,
    thumbnail_url: null,
    created_at: "2026-03-29T10:10:00Z",
    processed_at: null,
  },
  {
    id: "mock-failed-1",
    source_url: "https://www.instagram.com/reel/private123/",
    platform: "instagram",
    category: "other",
    status: "failed",
    extracted_data: null,
    action_taken: null,
    thumbnail_url: null,
    created_at: "2026-03-28T18:00:00Z",
    processed_at: null,
  },
];
