import { StyleSheet } from "react-native";

/** Shared styles for the item card and its category-specific body renderers. */
export const cardStyles = StyleSheet.create({
  card: {
    backgroundColor: "#161616",
    borderRadius: 12,
    borderLeftWidth: 4,
    borderColor: "#161616",
    marginHorizontal: 16,
    marginBottom: 12,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 6,
  },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 6, flexShrink: 0 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, flexShrink: 1 },
  chip: { backgroundColor: "#2a2a2a", borderRadius: 5, paddingHorizontal: 6, paddingVertical: 2 },
  chipText: { fontSize: 10, fontWeight: "600", color: "#bbb", textTransform: "uppercase", letterSpacing: 0.4 },
  statusPending: { fontSize: 10, color: "#f59e0b", backgroundColor: "#f59e0b1f", borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 },
  statusProcessing: { fontSize: 10, color: "#6366f1", backgroundColor: "#6366f11f", borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 },
  statusFailed: { fontSize: 10, color: "#ef4444", backgroundColor: "#ef44441f", borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 },
  timestamp: { fontSize: 11, color: "#777" },
  thumbnail: { width: "100%", height: 160, backgroundColor: "#222" },
  body: { paddingHorizontal: 14, paddingVertical: 8 },
  bodyGap: { gap: 6 },
  bodyTitle: { fontSize: 15, fontWeight: "600", color: "#f2f2f2" },
  bodySecondary: { fontSize: 12, color: "#aaa" },
  bodyQuote: { fontSize: 12, color: "#bbb", fontStyle: "italic", borderLeftWidth: 2, borderLeftColor: "#f9731650", paddingLeft: 8 },
  sectionLabel: { fontSize: 10, fontWeight: "600", color: "#888", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 2 },
  listItem: { fontSize: 12, color: "#bbb", marginTop: 2 },
  muted: { fontSize: 12, color: "#888" },
  urlText: { fontSize: 11, color: "#666", fontFamily: "Courier" },
  errorText: { fontSize: 12, color: "#ef4444" },
  retryButton: { alignSelf: "flex-start", backgroundColor: "#ef44441f", borderColor: "#ef444450", borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, marginTop: 2 },
  retryLabel: { fontSize: 12, fontWeight: "600", color: "#ef4444" },
  exerciseRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 2 },
  exerciseReps: { fontSize: 11, color: "#ef4444", fontFamily: "Courier" },
  footer: { flexDirection: "row", paddingHorizontal: 14, paddingVertical: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "#2a2a2a" },
  actionButton: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 9, alignSelf: "flex-start" },
  actionLabel: { fontSize: 12, fontWeight: "600" },
});
