import type { Metadata } from "next";
import { LegalLayout } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms and Conditions — fileaway",
  description: "The rules for using fileaway.",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms and Conditions" lastUpdated="May 16, 2026">
      <section>
        <p>
          Welcome to fileaway (&quot;fileaway&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). These
          Terms and Conditions (the &quot;Terms&quot;) govern your access to and use of the fileaway
          website, application, and related services (collectively, the &quot;Service&quot;). By creating
          an account or otherwise using the Service, you agree to be bound by these Terms. If you do
          not agree, do not use the Service.
        </p>
      </section>

      <section>
        <h2>1. The Service</h2>
        <p>
          fileaway lets you save links to publicly available social media posts (currently TikTok and
          Instagram, with other platforms supported on a best-effort basis) and uses third-party
          artificial intelligence models to categorize each post and extract structured information
          from it — for example, restaurant details, recipes, fitness routines, or step-by-step
          instructions. We may add, remove, or change features at any time.
        </p>
      </section>

      <section>
        <h2>2. Eligibility</h2>
        <p>
          You must be at least 13 years old to use the Service. If you are under the age of majority
          in your jurisdiction, you may only use the Service with the involvement of a parent or
          guardian. By using the Service, you represent that you meet these requirements.
        </p>
      </section>

      <section>
        <h2>3. Accounts</h2>
        <p>
          You can create an account using an email and password, or by signing in with a supported
          third-party provider such as Google or GitHub. You are responsible for:
        </p>
        <ul>
          <li>Providing accurate information and keeping it up to date.</li>
          <li>Keeping your credentials confidential and secure.</li>
          <li>All activity that occurs under your account.</li>
        </ul>
        <p>
          Notify us immediately if you suspect unauthorized access to your account. We are not liable
          for any loss arising from your failure to safeguard your credentials.
        </p>
      </section>

      <section>
        <h2>4. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to violate any law or third-party right, including intellectual property and privacy rights.</li>
          <li>Submit URLs that point to content that is illegal, infringing, harassing, hateful, sexually explicit involving minors, or otherwise objectionable.</li>
          <li>Attempt to bypass authentication, rate limits, or other access controls; reverse engineer the Service; or interfere with its operation.</li>
          <li>Use automated means to submit URLs at a volume or rate that is not consistent with ordinary individual use.</li>
          <li>Use the Service to compete with us or to build a substantially similar product.</li>
          <li>Resell, sublicense, or otherwise commercially exploit the Service or any data generated by it without our prior written consent.</li>
        </ul>
      </section>

      <section>
        <h2>5. Your content and saved links</h2>
        <p>
          When you submit a URL or other input to the Service, you represent that you have the right
          to do so. We do not claim ownership of the URLs you submit. You grant us a worldwide,
          non-exclusive, royalty-free license to host, store, process, transmit, and display that
          input — and any data we derive from it — solely to operate, provide, secure, and improve
          the Service for you.
        </p>
        <p>
          You can delete your saved items at any time from within the Service. Deletion removes the
          item from your account; residual copies may persist for a limited period in backups or
          logs.
        </p>
      </section>

      <section>
        <h2>6. Third-party content and platforms</h2>
        <p>
          The Service retrieves and processes publicly available content from third-party platforms
          (such as TikTok and Instagram) via third-party data providers. We do not own that content
          and have no control over the platforms or what they make available. Use of those platforms
          is governed by their own terms; you are responsible for complying with them when you save
          a link.
        </p>
        <p>
          The Service may stop working with any platform at any time, including because the platform
          changes its policies or technical interfaces.
        </p>
      </section>

      <section>
        <h2>7. AI-generated output</h2>
        <p>
          Categorization, summaries, ingredient lists, step-by-step guides, location lookups, and
          other structured fields are produced by third-party AI models from content we did not
          create. They can be wrong, incomplete, biased, or out of date. Do not rely on AI output
          for decisions involving health, safety, finance, or legal matters without independent
          verification. You use AI-generated output at your own risk.
        </p>
      </section>

      <section>
        <h2>8. Our intellectual property</h2>
        <p>
          The Service, including its source code, design, look and feel, trademarks, and the
          fileaway name and logo, is owned by us or our licensors and is protected by intellectual
          property laws. These Terms do not transfer any of those rights to you. We grant you a
          limited, revocable, non-exclusive, non-transferable license to use the Service for its
          intended purpose.
        </p>
      </section>

      <section>
        <h2>9. Feedback</h2>
        <p>
          If you send us feedback or suggestions, you grant us a perpetual, irrevocable, worldwide,
          royalty-free license to use them for any purpose without obligation to you.
        </p>
      </section>

      <section>
        <h2>10. Termination</h2>
        <p>
          You can stop using the Service and delete your account at any time. We may suspend or
          terminate your access at any time, with or without notice, if we reasonably believe you
          have violated these Terms or pose a risk to us, other users, or third parties. Sections
          that by their nature should survive (including ownership, disclaimers, limitation of
          liability, indemnity, and governing law) will survive termination.
        </p>
      </section>

      <section>
        <h2>11. Disclaimers</h2>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES
          OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, OR
          AVAILABILITY. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE,
          SECURE, OR THAT THE OUTPUT WILL BE ACCURATE OR USEFUL.
        </p>
      </section>

      <section>
        <h2>12. Limitation of liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL FILEAWAY, ITS AFFILIATES, OR ITS
          SUPPLIERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR
          PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING OUT OF
          OR RELATED TO YOUR USE OF THE SERVICE. OUR TOTAL CUMULATIVE LIABILITY FOR ALL CLAIMS
          RELATED TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID US IN THE
          TWELVE MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) USD $50.
        </p>
      </section>

      <section>
        <h2>13. Indemnity</h2>
        <p>
          You will defend, indemnify, and hold us harmless from any claim, demand, loss, or expense
          (including reasonable attorneys&apos; fees) arising out of (a) your use of the Service,
          (b) the URLs or other content you submit, (c) your violation of these Terms, or (d) your
          violation of any law or third-party right.
        </p>
      </section>

      <section>
        <h2>14. Changes to the Service or Terms</h2>
        <p>
          We may modify these Terms at any time. If we make material changes we will update the
          &quot;Last updated&quot; date above and, where appropriate, provide additional notice.
          Your continued use of the Service after changes take effect constitutes acceptance of the
          updated Terms.
        </p>
      </section>

      <section>
        <h2>15. Governing law and disputes</h2>
        <p>
          These Terms are governed by the laws of the jurisdiction in which fileaway is operated,
          without regard to its conflict of laws principles. You and we agree to submit to the
          exclusive jurisdiction of the courts located in that jurisdiction for any dispute arising
          out of or related to these Terms or the Service, except where prohibited by applicable
          consumer-protection law.
        </p>
      </section>

      <section>
        <h2>16. Miscellaneous</h2>
        <p>
          These Terms are the entire agreement between you and us regarding the Service and
          supersede any prior agreements. If any provision is held unenforceable, the remaining
          provisions remain in effect. Our failure to enforce a provision is not a waiver of our
          right to enforce it later. You may not assign these Terms; we may assign them in
          connection with a corporate transaction.
        </p>
      </section>

      <section>
        <h2>17. Contact</h2>
        <p>
          Questions about these Terms? Reach us at{" "}
          <a href="mailto:hello@fileaway.app">hello@fileaway.app</a>.
        </p>
      </section>
    </LegalLayout>
  );
}
